defaults:
  - sampling: sampling_strategies
  - compilation: compile_torch
  - _self_

# checkpoint_path: ./outputs/2025-05-14/23-17-50/checkpoints/latest/ # p_u = 0.0
# checkpoint_path: ./outputs/2025-05-14/23-14-12/checkpoints/latest/ # p_u = 0.1
# checkpoint_path: ./outputs/2025-05-15/11-54-08/checkpoints/latest/ # p_u = 0.2
# checkpoint_path: ./outputs/2025-05-17/12-00-07/checkpoints/latest/ # p_u = 0.1
# checkpoint_path: ./outputs/2025-05-23/15-40-25/checkpoints/latest/ # p_u = 0.0
# checkpoint_path: ./outputs/2025-05-24/11-02-09/checkpoints/latest/ # p_u = 0.1
checkpoint_path:
  # - ./outputs/2025-05-26/17-20-34/checkpoints/latest/ # p_u = 0.0, lw=dynamic
  # - ./outputs/2025-05-26/17-21-29/checkpoints/latest/ # p_u = 0.0, lw=none
  # - ./outputs/2025-05-27/14-50-38/checkpoints/latest/ # p_u = 0.1, lw=dynamic
  - ./outputs/2025-06-01/17-31-45/checkpoints/latest/ # p_u = 0.0, lw=none, epochs = 50
  - ./outputs/2025-06-03/11-03-14/checkpoints/latest/ # p_u = 0.0, lw=dynamic, epochs = 10
  - ./outputs/2025-06-03/11-04-13/checkpoints/latest/ # p_u = 0.0, lw=clip, epochs = 10
  - ./outputs/2025-06-03/15-51-51/checkpoints/latest/ # p_u = 0.1, lw=none, epochs = 10

batch_size: 64
num_denoising_steps: 81 # 90 # 50 # 128
min_p: 0.0