defaults:
  - logging: default
  # - data: owt
  # - model: small
  - data: sudoku
  - model: 6M
  - optimizer: adam
  - sampling: training_sampling
  - compilation: compile_torch
  - _self_

model:
  type: diffusion
  diffusion_process: gidd
  p_uniform: 0.0
  t_eps: 1e-4
  puzzle_conditioning: none # [none, cross_attention, in_context]

training:
  resume: null
  seed: 1
  train_batch_size: 128 # 64
  eval_batch_size: 64
  score_batch_size: 64
  # num_train_steps: 1 epoch = 1_889_993 / 64 = 29_532
  # for shah: 1 epoch = 1_704_462 samples, 1_704_462 / 128 = 13_316.109
  num_train_steps: 134_000 # 236_256 # 118_128
  lr_schedule: cosine # [cosine, linear, constant]
  warmup_steps: 10_000 #10000
  low_discrepancy_sampling: True
  dtype: bf16
  use_diffusion_mask: True

loss:
  loss_type: gidd
  loss_weighting: none  # [dynamic, clip, none]
  min_loss_weight: 0.0
  max_loss_weight: 2.0
  loss_scale: 1.0
  reduction: tokenmean
