position_metric: # [MDM_max, MDM_margin, MDM_margin_relative, max, margin]
  - MDM_max
  # - MDM_margin
  # - MDM_margin_relative
position_sampling_strategy: # [independent, all, top_k_gumbel, top_k, top_p, min_p]
  # - independent
  # - all
  - top_k_gumbel
position_sampling_strategy_args:
  top_k_gumbel:
    k:
      - 1
      # - 2
      # - 8
      # - 20
    gumbel_noise_coefficient:
      - 0.0
      # - 0.1
      # - 0.01
      # - 0.001
  top_k: 8
  top_p: 0.9
  min_p: 0.05
token_sampling_strategy: # [MDM_max, MDM_categorical, categorical, top_k, top_p, min_p]
  - MDM_max
  - MDM_categorical
  # - categorical
token_sampling_strategy_args:
  top_k: 10
  top_p: 0.9
  min_p: 0.05